[build]
builder = "nixpacks"
watchPatterns = ["apps/api/**", "packages/**", "prisma/**"]

[deploy]
startCommand = "./scripts/railway-deploy.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"
PRISMA_POOL_TIMEOUT = "30"
PRISMA_CLIENT_ENGINE_TYPE = "library"

[environments.production.deploy]
startCommand = "./scripts/railway-deploy.sh"