[build]
builder = "NIXPACKS"
watchPatterns = ["apps/api/**"]

[deploy]
startCommand = "cd apps/api && pnpm start"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[environments.production]
variables = { NODE_ENV = "production", PORT = "3001" }