version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trgdb
      POSTGRES_USER: trg_app
      POSTGRES_PASSWORD: 8c44649ab86d78eb9d7393ac105cf7fa
    volumes:
      - trg_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tradygo

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    env_file:
      - ./env/api.env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - tradygo

  admin:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.admin
    env_file:
      - ./env/admin.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - tradygo

  caddy:
    image: caddy:2.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - admin
      - api
    restart: unless-stopped
    networks:
      - tradygo

volumes:
  trg_db_data:
  caddy_data:
  caddy_config:

networks:
  tradygo:
    driver: bridge